name: Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: vijayb47
  RESOURCE_GROUP: rg-aks-portal-sandbox
  CLUSTER_NAME: aks-portal-sandbox
  IMAGE_TAG: ${{ github.sha }}
  environment: sandbox

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/backend:${{ env.IMAGE_TAG }} ./backend
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/backend:latest ./backend
        docker push ${{ env.DOCKERHUB_USERNAME }}/backend:${{ env.IMAGE_TAG }}
        docker push ${{ env.DOCKERHUB_USERNAME }}/backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ env.IMAGE_TAG }} ./frontend
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
        docker push ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ env.IMAGE_TAG }}
        docker push ${{ env.DOCKERHUB_USERNAME }}/frontend:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install kubelogin
      run: |
        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.32/kubelogin-linux-amd64.zip
        unzip kubelogin-linux-amd64.zip
        sudo mv bin/linux_amd64/kubelogin /usr/local/bin/
        sudo chmod +x /usr/local/bin/kubelogin
        
    # - name: Set AKS context
    #   uses: azure/aks-set-context@v3
    #   with:
    #     resource-group: ${{ env.RESOURCE_GROUP }}
    #     cluster-name: ${{ env.CLUSTER_NAME }}
        
    - name: Set AKS context with Azure CLI auth
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --overwrite-existing
        kubelogin convert-kubeconfig -l azurecli
        
    - name: Deploy to AKS
      run: |
        # Replace placeholders in YAML files
        export DOCKERHUB_USERNAME=${{ env.DOCKERHUB_USERNAME }}
        export IMAGE_TAG=${{ env.IMAGE_TAG }}
        
        for file in k8s/*.yaml; do
          envsubst < $file | kubectl apply -n portal -f -
        done

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/backend  -n portal
        kubectl rollout status deployment/frontend  -n portal
        kubectl get services  -n portal